---
Name: tinypngconfig
---

SilverStripe\Assets\Image:
  extensions:
  - Kinglozzer\SilverStripeTinyPng\ImageExtension

SilverStripe\Assets\Storage\DBFile:
  extensions:
  - Kinglozzer\SilverStripeTinyPng\ImageExtension
